# Generated by Django 2.0 on 2018-01-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_edited_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='edited_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
