# Generated by Django 2.0 on 2018-01-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180101_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='edited_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
